import React, { useState } from 'react';
import { View, TextInput, Button, StyleSheet } from 'react-native';
import { DataStore } from '@aws-amplify/datastore';
import { Expense } from '../models'; // Import the model generated by Amplify

const AddExpenseScreen = ({ navigation }) => {
  const [title, setTitle] = useState('');
  const [amount, setAmount] = useState('');

  const handleAddExpense = async () => {
    if (!title || !amount) {
      alert('Please provide both title and amount.');
      return;
    }

    try {
      // Save the expense to the DataStore
      await DataStore.save(
        new Expense({
          title,
          amount: parseFloat(amount),
        })
      );
      navigation.navigate('ExpenseList');
    } catch (err) {
      console.error('Error saving expense: ', err);
      alert('Error saving expense. Please try again.');
    }
  };

  return (
    <View style={styles.container}>
      <TextInput
        style={styles.input}
        placeholder="Expense Title"
        value={title}
        onChangeText={setTitle}
      />
      <TextInput
        style={styles.input}
        placeholder="Amount"
        value={amount}
        onChangeText={setAmount}
        keyboardType="numeric"
      />
      <Button title="Add Expense" onPress={handleAddExpense} />
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, justifyContent: 'center', padding: 16 },
  input: { borderWidth: 1, borderColor: '#ddd', marginBottom: 12, padding: 8 }
});

export default AddExpenseScreen;

